2022-01-28 17:14:37,501:data_com_logs.txt:INFO:-------------------Starting application-------------------
2022-01-28 17:14:37,873:data_com_logs.txt:DEBUG:MariaDB.py : Connected to database
2022-01-28 17:14:52,897:data_com_logs.txt:DEBUG:INCOMING MSG FROM BDD : (11, '00000002', 'EEEEEE00', '42', '08', 'CAFEDECA', datetime.datetime(2022, 1, 24, 9, 55, 20), 1)
2022-01-28 17:14:55,565:data_com_logs.txt:DEBUG:Message successfully sent to UART : 1100000002EEEEEE004208CAFEDECA
2022-01-28 17:15:02,960:data_com_logs.txt:DEBUG:INCOMING MSG FROM UART : BA1000000002EEEEEE00A2420508CAFEDECADA
2022-01-28 17:15:02,965:data_com_logs.txt:DEBUG:Parsed message : <data_communication.FrameParser.FrameParser object at 0x7fcaf6b7c280>
2022-01-28 17:15:03,015:data_com_logs.txt:DEBUG:Request successfully sent to DataBase
2022-01-28 17:15:07,913:data_com_logs.txt:DEBUG:INCOMING MSG FROM BDD : (11, '00000002', 'EEEEEE00', '42', '08', 'CAFEDECA', datetime.datetime(2022, 1, 24, 9, 55, 20), 1)
2022-01-28 17:15:08,966:data_com_logs.txt:DEBUG:Message successfully sent to UART : 1100000002EEEEEE004208CAFEDECA
